sudo: required
services:
    - docker

before_install:
    - docker build -t inferno24/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true inferno24/docker-react npm run test


# FOR DEPLOYING THE APPLICATION TO AWS

# deploy:
#     provider: elasticbeanstalk
#     region: "ap-south-1"
#     app: "docker"
#     env: "Docker-env"
#     bucket_name: "elasticbeanstalk-ap-south-1-720370103543"
#     bucket_path: "docker"
#     on:
#         branch: master
#     access_key_id: $AWS_ACCESS_ID
#     secret_access_key: $AWS_SECRET_KEY
    













